"""Consolidated evaluation of the validity JUDGE (final system, 2D features).

The judge is machine-learning based and evaluated per criterion, each with coherent
data (rather than one monolithic model, which is fragile with a single subject).
Reproducible:

  1) DEPTH, multi-view: ML on 2D depth + knee + the view as context, real reps,
     leave-one-take-out. Compared against the rule baseline (single threshold and
     per-view threshold). The ML learns each view's scale.
  2) LOCKOUT: ML on 2D features, augmented with counterfactual no-reps generated by
     cropping real valid reps; evaluated on the real lockout per view.

Judge metric: accuracy and FALSE-ACCEPT RATE (a no-rep passed as valid).
Reads squat/data/cache/grabaciones_2d/.
"""
import json
import os

import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier

from squat.application.counterfactual import (lockout_window, real_features,
                                              rep_windows_from_bottoms)
from squat.application.rich_features import rich_features
from squat.domain.validation import INVALIDA_LOCKOUT, INVALIDA_PROFUNDIDAD, VALIDA

REC2D = os.path.join(os.path.dirname(__file__), "..", "data", "cache", "grabaciones_2d")
VIEWS = ["lateral", "frontal", "45deg"]
DEPTH_COL, HIP_COL = 0, 8  # rich_features: depth_max, hip_max
LOCK_TARGETS = [148, 152, 156, 160, 164]


def load():
    X, W, y, view, take = [], [], [], [], []
    for it in json.load(open(os.path.join(REC2D, "manifest.json")))["items"]:
        d = np.load(os.path.join(REC2D, it["key"] + ".npz"), allow_pickle=True)
        for w, lab in zip(rep_windows_from_bottoms(d["features"], d["bottoms"]),
                          [str(x) for x in d["labels"]]):
            X.append(rich_features(w)); W.append(w); y.append(lab)
            view.append(it["perspective"]); take.append(it["take"])
    return np.array(X, np.float32), W, np.array(y), np.array(view), np.array(take)


def fa_acc(sh, pred):
    acc = (pred == sh).mean()
    fa = (~pred[sh]).mean() if sh.any() else 0.0  # positives (no-rep) missed
    return acc, fa


def by_view(title, sh, pred, view):
    print(f"\n{title}")
    print(f"{'view':8} {'n':>4} {'acc':>6} {'false-acc':>12}")
    for v in VIEWS + ["GLOBAL"]:
        m = np.ones(len(sh), bool) if v == "GLOBAL" else (view == v)
        if m.sum():
            a, fa = fa_acc(sh[m], pred[m])
            print(f"{v:8} {int(m.sum()):4} {a:6.2f} {fa:11.1%}")


def calib(depth, sh):
    best = (None, -1)
    for thr in np.quantile(depth, np.linspace(0.05, 0.95, 80)):
        acc = ((depth < thr) == sh).mean()
        if acc > best[1]:
            best = (float(thr), acc)
    return best[0]


def depth_judge(X, y, view, take):
    m = np.isin(y, [VALIDA, INVALIDA_PROFUNDIDAD])
    X, view, take = X[m], view[m], take[m]
    sh = (y[m] == INVALIDA_PROFUNDIDAD)
    depth = X[:, DEPTH_COL]
    print("\n" + "=" * 62 + "\nCRITERION 1 — DEPTH (multi-view, 2D)\n" + "=" * 62)

    thr = calib(depth[view == "lateral"], sh[view == "lateral"])
    by_view(f"(baseline) RULE, SINGLE threshold (lateral, {thr:+.3f})", sh, depth < thr, view)

    y2 = np.zeros(len(sh), bool)
    for v in VIEWS:
        mv = view == v
        y2[mv] = depth[mv] < calib(depth[mv], sh[mv])
    by_view("(baseline) RULE, PER-VIEW threshold", sh, y2, view)

    oh = np.stack([(view == v).astype(np.float32) for v in VIEWS], axis=1)
    Xc = np.column_stack([X[:, [DEPTH_COL, 1, 4]], oh])  # depth, knee_r, knee_min proxy + view
    pred = np.empty(len(sh), bool)
    for t in np.unique(take):
        te = take == t
        clf = HistGradientBoostingClassifier(max_iter=300, learning_rate=0.08,
                                             max_depth=3, random_state=0)
        clf.fit(Xc[~te], sh[~te]); pred[te] = clf.predict(Xc[te]).astype(bool)
    by_view(">>> ML VALIDATOR (2D depth + view)", sh, pred, view)


def lockout_judge(X, W, y, view, take):
    print("\n" + "=" * 62 + "\nCRITERION 2 — LOCKOUT (2D + counterfactual)\n" + "=" * 62)
    m = np.isin(y, [VALIDA, INVALIDA_LOCKOUT])
    Xr, Wr, viewr, taker = X[m], [W[i] for i in np.where(m)[0]], view[m], take[m]
    yr = y[m]; sh = (yr == INVALIDA_LOCKOUT)
    pred = np.empty(len(sh), bool)
    for t in np.unique(taker):
        te = taker == t; tr = ~te
        # lockout counterfactuals from the real valid reps in the train takes
        Xcf = []
        for i in np.where(tr & (yr == VALIDA))[0]:
            for tgt in LOCK_TARGETS:
                lw = lockout_window(Wr[i], tgt)
                if lw is not None:
                    Xcf.append(rich_features(lw))
        Xtr = np.vstack([Xr[tr], np.array(Xcf, np.float32)]) if Xcf else Xr[tr]
        ytr = np.concatenate([sh[tr], np.ones(len(Xcf), bool)]) if Xcf else sh[tr]
        clf = HistGradientBoostingClassifier(max_iter=300, learning_rate=0.08,
                                             max_depth=3, random_state=0)
        clf.fit(Xtr, ytr); pred[te] = clf.predict(Xr[te]).astype(bool)
    by_view(">>> ML VALIDATOR (2D lockout + counterfactual)", sh, pred, viewr)


def main():
    X, W, y, view, take = load()
    print(f"recordings (2D): {len(y)} reps {dict(zip(*np.unique(y, return_counts=True)))}")
    depth_judge(X, y, view, take)
    lockout_judge(X, W, y, view, take)


if __name__ == "__main__":
    main()
